/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 gaming.gltf 
Author: BiscuitDz (https://sketchfab.com/BiscuitDz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-rifle-free-use-60682dacf78e40398b570280a27a2135
Title: Low Poly Rifle - Free Use
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/gaming.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, -0.135, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Front_Hand_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Front_Hand_Material008_0.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Front_Hand_Material004_0.geometry} material={materials['Material.004']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Body_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Body_Material005_0.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Body_Material008_0.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Body_Material004_0.geometry} material={materials['Material.004']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Silencer_Material002_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Silencer_Material006_0.geometry} material={materials['Material.006']} />
          </group>
          <mesh geometry={nodes.Barrel_Material008_0.geometry} material={materials['Material.008']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Stock_Material008_0.geometry} material={materials['Material.008']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Mag_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gaming.gltf')
