/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 music.gltf 
Author: Luka.Aleksic (https://sketchfab.com/Luka.Aleksic)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/maxell-retro-dj-headphones-12b62f361fa54e1d8a5bf9a3aaa7322b
Title: Maxell Retro DJ Headphones
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/music.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.016, -1.399]}>
        <group position={[-0.941, 1.401, 0]} rotation={[Math.PI / 2, 0.964, -Math.PI / 2]} scale={[0.14, 0.14, 0.037]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials.leather} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.leather} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.leather} />
        </group>
        <group position={[-0.966, 0.866, 0]} rotation={[-Math.PI, 0, -0.169]} scale={[-0.029, 0.087, 0.128]}>
          <mesh geometry={nodes.Object_9.geometry} material={materials.plastic_rough} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.metal_rough} />
        </group>
        <group rotation={[Math.PI, 0, 2.443]}>
          <mesh geometry={nodes.Object_20.geometry} material={materials.leather} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.leather} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.metal_rough} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.plastic_shiny} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.plastic_rough} />
        </group>
        <mesh geometry={nodes.Object_12.geometry} material={materials.metal_rough} position={[-0.927, 1.288, -0.002]} rotation={[0, 0, -1.83]} scale={0.02} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.plastic_shiny} position={[-0.277, 0.01, 0]} rotation={[0, 0, -2.591]} scale={0.027} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.graytext} position={[-0.295, 0.127, 0.163]} rotation={[1.125, 0.674, -1.396]} scale={[-0.057, 0.057, 0.057]} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.graytext} position={[0.338, 0.095, -0.193]} rotation={[2.132, -0.713, -1.274]} scale={0.057} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.leather} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.leather} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.whiteletter} position={[-1.001, 0.864, -0.022]} rotation={[1.558, 0.169, 1.573]} scale={0.086} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.maxelllogo} position={[0.772, 0.205, 0.005]} rotation={[1.525, -0.698, -1.6]} scale={[0.135, 0.135, 0.083]} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.whiteletter} position={[1, 0.855, 0.023]} rotation={[1.563, -0.169, -1.572]} scale={0.086} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.metal_rough} position={[0, 1.1, 0]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/music.gltf')
