/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Tennis.gltf 
Author: Ya (https://sketchfab.com/Yarik16)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/wilson-blade-team-tennis-racket-c9db9da0832341cf843b3b5abe615c38
Title: Wilson Blade Team Tennis Racket
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Tennis.gltf')

  if (materials.tennis_racquet) {
    materials.tennis_racquet.color.set('#000000'); // Black color
    materials.tennis_racquet.needsUpdate = true;
  }

  if (materials.strings) {
    materials.strings.color.set('#000000'); // Black color
    materials.strings.needsUpdate = true;
  }

  if (materials.dark) {
    materials.dark.color.set('#000000'); // Black color
    materials.dark.needsUpdate = true;
  }

  return (
    <group {...props} dispose={null}  rotation={[Math.PI / 4, Math.PI / 4, 0]}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.tennis_racquet} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.strings} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.dark} />
    </group>
  )
}

useGLTF.preload('/Tennis.gltf')
